### ISSUE TITLE
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: XcbConnect(DisplayParsingError)', /home/ketan/.cargo/registry/src/github.com-1ecc6299db9ec823/a-gpt-0.1.14/src/util.rs:36:43 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

### ISSUE THREAD

**Issue by ket000** [ddddddeon/a#5]
Getting below error on ubuntu 18.04

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: XcbConnect(DisplayParsingError)', /home/ketan/.cargo/registry/src/github.com-1ecc6299db9ec823/a-gpt-0.1.14/src/util.rs:36:43
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by ket000** [comment]
Thanks for the update. I was running it in non gui environment. X11 is configured and running but terminal was not launched from gui environment. I did installed the dependencies for clipboard environment. I will try to uninstall and reinstall without clipboard support. I typically try not to use x11 gui as it slows down by old laptop and try to generally use tui (terminal based apps) if possible, and it is easier to access from ipad as there is no way to run x11 server on ios.

**Comment by ket000** [comment]
After following your advice and using no clipboard version , I am able to use it with no issues. Thank you for all the help.

**Comment by ddddddeon** [comment]
My pleasure! Thanks for pointing this out for me.
